# Generated by Django 4.0 on 2021-12-11 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=20)),
                ('state', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=20)),
                ('phone', models.IntegerField()),
                ('company_name', models.CharField(max_length=15)),
                ('logo', models.ImageField(upload_to='uploads/application')),
                ('team_background', models.CharField(max_length=500)),
                ('company_products', models.CharField(max_length=500)),
                ('incubation_type', models.CharField(max_length=50)),
                ('status', models.CharField(default='Applied', max_length=20)),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
