# Generated by Django 4.0 on 2021-12-11 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationform',
            name='phone',
            field=models.CharField(max_length=20),
        ),
    ]
