# Generated by Django 4.0 on 2021-12-11 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0005_alter_applicationform_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationform',
            name='address',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='applicationform',
            name='city',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='applicationform',
            name='company_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='applicationform',
            name='incubation_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='applicationform',
            name='phone',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='applicationform',
            name='state',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='applicationform',
            name='status',
            field=models.CharField(default='Applied', max_length=50),
        ),
    ]
